#!/bin/sh

# These directories are reported missing for some reason, most likely build tools error

mkdir -p ./pasterino/build/intermediates/data-binding-info/androidTest/debug
mkdir -p ./pasterino/build/intermediates/data-binding-layout-out/androidTest/debug
